from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from jinja2 import Template


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AWS Inventory Dashboard</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 24px; }
        table { border-collapse: collapse; width: 100%; margin-top: 12px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background: #f4f4f4; }
        tbody tr:nth-child(even) { background: #fafafa; }
        .summary { margin-top: 12px; }
    </style>
</head>
<body>
    <h1>AWS Inventory Dashboard</h1>
    <p class="summary">This report was generated by AWS-Inventory-Tool and includes inventory counts for each selected service.</p>

    <table>
        <thead>
            <tr>
                <th>Service</th>
                <th>Report File</th>
                <th>Item Count</th>
            </tr>
        </thead>
        <tbody>
            {% for item in reports %}
            <tr>
                <td>{{ item.name }}</td>
                <td><a href="{{ item.filename }}">{{ item.filename }}</a></td>
                <td>{{ item.count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>
"""


@dataclass
class HtmlReportEntry:
    name: str
    filename: str
    count: int


def write_html_report(output_path: Path, reports: Sequence[HtmlReportEntry]) -> Path:
    html_path = output_path / "inventory_dashboard.html"
    template = Template(HTML_TEMPLATE)
    html_content = template.render(reports=reports)
    html_path.write_text(html_content, encoding="utf-8")
    return html_path
